# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3ViMLr73rFaVxuunt0v6C7NHeJldSpk
"""

a = (float(input("hãy nhập số chiều dài:")))
b = (float(input("hãy nhập chiều rộng:")))

dien_tich= a*b
chu_vi= (a+b)*2

N = int(input("Hãy nhập số ngẫu nhiên:"))
if N%2==0 and N%3==0:
  print("N chia hết cho 3")
else:
  print("N không chia hết cho 3")

a= int(input("Hãy nhập số muốn in ra:"))
for x in range(a)
print (x+1)