# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3ViMLr73rFaVxuunt0v6C7NHeJldSpk
"""


x=0
x2=10
n = int(input("Hãy nhập số x:"))
for i in range (1,n+1):
  x += i/(i-1)
print (S1)
for j in range (1,n+1):
  x2 += (j-1)/j
print (S2)
